import { ProductType } from './types';

export const products: ProductType[] = [
  {
    id: 'smart-watch-pro',
    name: 'Smart Watch Pro',
    description: 'Advanced smartwatch with health monitoring and notifications.',
    fullDescription: 'The Smart Watch Pro is a premium wearable device designed for those who want to stay connected and monitor their health. With its advanced sensors, you can track your heart rate, sleep patterns, and daily activity. It also provides notifications from your smartphone, so you never miss an important call or message. The sleek design makes it suitable for both casual and formal occasions.',
    price: 249.99,
    originalPrice: 299.99,
    image: 'https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    images: [
      'https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      'https://images.pexels.com/photos/393047/pexels-photo-393047.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      'https://images.pexels.com/photos/4064935/pexels-photo-4064935.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'
    ],
    categoryId: 'electronics',
    brand: 'TechGear',
    model: 'SW-Pro-2023',
    rating: 4.7,
    reviewCount: 128,
    inStock: true,
    featured: true,
    sale: true,
    color: 'Black',
    dimensions: '44mm x 38mm x 10.7mm',
    weight: '48g',
    material: 'Aluminum and sapphire glass',
    warranty: '2 years limited warranty',
    features: [
      'Heart rate and ECG monitoring',
      'Sleep tracking',
      'GPS and fitness tracking',
      'Water resistant up to 50m',
      'Up to 3 days battery life',
      'Customizable watch faces',
      'Notification support'
    ]
  },
  {
    id: 'wireless-earbuds',
    name: 'Premium Wireless Earbuds',
    description: 'High-quality wireless earbuds with noise cancellation and long battery life.',
    fullDescription: 'Experience premium sound quality with these wireless earbuds. Featuring active noise cancellation, these earbuds allow you to enjoy your music without any distractions. The ergonomic design ensures a comfortable fit for extended wear, and the long battery life means you can listen all day without recharging. Perfect for commuting, working out, or just relaxing at home.',
    price: 129.99,
    originalPrice: 159.99,
    image: 'https://images.pexels.com/photos/3780681/pexels-photo-3780681.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    categoryId: 'electronics',
    brand: 'SoundWave',
    model: 'SW-E300',
    rating: 4.5,
    reviewCount: 94,
    inStock: true,
    featured: true,
    sale: true,
    color: 'White',
    weight: '5g per earbud, 45g case',
    material: 'Plastic and silicone',
    warranty: '1 year limited warranty',
    features: [
      'Active noise cancellation',
      'Bluetooth 5.2 connectivity',
      'Touch controls',
      'Up to 8 hours playback (24 with case)',
      'IPX5 water resistance',
      'Quick charge: 10 min for 2 hours'
    ]
  },
  {
    id: 'premium-laptop',
    name: 'Ultra Slim Laptop Pro',
    description: 'Powerful laptop with high-performance specs in an ultra-slim design.',
    fullDescription: 'The Ultra Slim Laptop Pro combines powerful performance with elegant design. Featuring the latest processor, ample RAM, and fast SSD storage, this laptop can handle everything from everyday tasks to demanding creative work. The high-resolution display delivers vibrant colors and sharp details, making it perfect for content creation and media consumption. Despite its powerful specs, the slim profile makes it easy to carry wherever you go.',
    price: 1299.99,
    image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    categoryId: 'electronics',
    brand: 'TechPro',
    model: 'X1500',
    rating: 4.8,
    reviewCount: 56,
    inStock: true,
    featured: true,
    new: true,
    color: 'Silver',
    dimensions: '12.8" x 8.9" x 0.6"',
    weight: '1.3kg',
    material: 'Aluminum',
    warranty: '2 years limited warranty',
    features: [
      '15.6" 4K Display',
      'Intel Core i7 processor',
      '16GB RAM, 512GB SSD',
      'Integrated graphics',
      'Backlit keyboard',
      'Fingerprint reader',
      'Up to 12 hours battery life'
    ]
  },
  {
    id: 'leather-jacket',
    name: 'Vintage Leather Jacket',
    description: 'Classic leather jacket with a vintage look and premium quality.',
    fullDescription: 'Add timeless style to your wardrobe with this vintage leather jacket. Made from premium quality leather, this jacket offers both durability and comfort. The classic design with subtle detailing makes it versatile enough to pair with both casual and semi-formal outfits. The soft inner lining provides warmth during colder months, while the multiple pockets offer practicality. A staple piece that will only get better with age.',
    price: 199.99,
    originalPrice: 249.99,
    image: 'https://images.pexels.com/photos/16170/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    categoryId: 'clothing',
    brand: 'Urban Style',
    rating: 4.6,
    reviewCount: 72,
    inStock: true,
    sale: true,
    color: 'Brown',
    material: 'Genuine leather',
    features: [
      'Genuine leather construction',
      'Soft polyester lining',
      'Multiple pockets',
      'Zip closure',
      'Adjustable cuffs'
    ]
  },
  {
    id: 'bluetooth-speaker',
    name: 'Portable Bluetooth Speaker',
    description: 'Compact and powerful Bluetooth speaker with impressive sound quality.',
    price: 79.99,
    image: 'https://images.pexels.com/photos/3780514/pexels-photo-3780514.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    categoryId: 'electronics',
    brand: 'SoundWave',
    rating: 4.4,
    reviewCount: 113,
    inStock: true,
    featured: false,
    color: 'Black',
    dimensions: '7.2" x 2.9" x 3.0"',
    weight: '0.8kg',
    features: [
      'Bluetooth 5.0 connectivity',
      'IPX7 waterproof',
      '20 hours playback',
      'Built-in microphone',
      'USB-C charging'
    ]
  },
  {
    id: 'home-decor-vase',
    name: 'Modern Ceramic Vase',
    description: 'Elegant ceramic vase with a modern design to enhance your home decor.',
    price: 39.99,
    image: 'https://images.pexels.com/photos/2119500/pexels-photo-2119500.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    categoryId: 'home',
    rating: 4.3,
    reviewCount: 42,
    inStock: true,
    new: true,
    color: 'White',
    dimensions: '10" x 5" x 5"',
    material: 'Ceramic',
    features: [
      'Hand-crafted ceramic',
      'Modern minimalist design',
      'Suitable for fresh or dried flowers',
      'Water-resistant finish'
    ]
  },
  {
    id: 'casual-sneakers',
    name: 'Comfort Casual Sneakers',
    description: 'Stylish and comfortable sneakers perfect for everyday wear.',
    price: 69.99,
    originalPrice: 89.99,
    image: 'https://images.pexels.com/photos/2421374/pexels-photo-2421374.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    categoryId: 'clothing',
    brand: 'WalkEasy',
    rating: 4.5,
    reviewCount: 89,
    inStock: true,
    sale: true,
    color: 'White/Gray',
    material: 'Synthetic leather and mesh',
    features: [
      'Memory foam insole',
      'Breathable mesh upper',
      'Rubber outsole',
      'Padded collar',
      'Lightweight design'
    ]
  },
  {
    id: 'chef-knife-set',
    name: 'Professional Chef Knife Set',
    description: 'High-quality knife set for professional cooking and food preparation.',
    price: 149.99,
    image: 'https://images.pexels.com/photos/3650438/pexels-photo-3650438.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    categoryId: 'home',
    brand: 'CulinaryPro',
    rating: 4.7,
    reviewCount: 64,
    inStock: true,
    featured: true,
    material: 'Stainless steel',
    warranty: '5 years limited warranty',
    features: [
      '8" Chef\'s knife',
      '7" Santoku knife',
      '5" Utility knife',
      '3.5" Paring knife',
      'Kitchen shears',
      'Knife sharpener',
      'Wooden block'
    ]
  },
  {
    id: 'designer-handbag',
    name: 'Luxury Designer Handbag',
    description: 'Elegant designer handbag made with premium materials and exquisite craftsmanship.',
    price: 299.99,
    image: 'https://images.pexels.com/photos/904350/pexels-photo-904350.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    categoryId: 'accessories',
    brand: 'LuxeStyle',
    rating: 4.8,
    reviewCount: 38,
    inStock: true,
    new: true,
    color: 'Tan',
    dimensions: '12" x 9" x 4"',
    material: 'Genuine leather',
    features: [
      'Genuine leather construction',
      'Gold-tone hardware',
      'Multiple compartments',
      'Interior zip pocket',
      'Adjustable shoulder strap',
      'Dust bag included'
    ]
  },
  {
    id: 'fitness-tracker',
    name: 'Advanced Fitness Tracker',
    description: 'Track your workouts, heart rate, and daily activity with this advanced fitness band.',
    price: 89.99,
    originalPrice: 109.99,
    image: 'https://images.pexels.com/photos/863988/pexels-photo-863988.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    categoryId: 'electronics',
    brand: 'FitTech',
    rating: 4.4,
    reviewCount: 115,
    inStock: true,
    sale: true,
    color: 'Black',
    dimensions: '8.5" x 0.8" x 0.4"',
    weight: '25g',
    warranty: '1 year limited warranty',
    features: [
      'Heart rate monitoring',
      'Sleep tracking',
      'Step counter',
      'Water resistant',
      '7-day battery life',
      'Smartphone notifications',
      'Companion app'
    ]
  },
  {
    id: 'coffee-maker',
    name: 'Premium Coffee Maker',
    description: 'Brew the perfect cup of coffee with this premium programmable coffee maker.',
    price: 129.99,
    image: 'https://images.pexels.com/photos/6898854/pexels-photo-6898854.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    categoryId: 'home',
    brand: 'BrewMaster',
    rating: 4.6,
    reviewCount: 77,
    inStock: true,
    featured: false,
    color: 'Stainless Steel',
    dimensions: '10" x 8" x 14"',
    warranty: '2 years limited warranty',
    features: [
      '12-cup capacity',
      'Programmable timer',
      'Brew strength selector',
      'Keep warm function',
      'Auto shut-off',
      'Water level indicator',
      'Removable filter basket'
    ]
  },
  {
    id: 'sunglasses',
    name: 'Polarized Aviator Sunglasses',
    description: 'Classic aviator sunglasses with polarized lenses for superior sun protection.',
    price: 59.99,
    image: 'https://images.pexels.com/photos/46710/pexels-photo-46710.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    categoryId: 'accessories',
    brand: 'ShadeStyle',
    rating: 4.5,
    reviewCount: 52,
    inStock: true,
    new: false,
    color: 'Gold/Green',
    material: 'Metal frame, glass lenses',
    features: [
      'Polarized lenses',
      'UV400 protection',
      'Adjustable nose pads',
      'Spring hinges',
      'Includes case and cleaning cloth'
    ]
  }
];